# Generated by AI on 2024-12-19
# Reviewed by: AI Assistant
# Ticket: SFIA-002

"""
Comparison script to show the difference between app answer and actual document content
"""

import pandas as pd

def get_actual_strategic_planning_level4():
    """Get the actual Level 4 description for Strategic planning from the document."""
    df = pd.read_excel('doc/sfia-9_current-standard_en_250129.xlsx', sheet_name='Skills')
    strategic_planning = df[df['Skill'] == 'Strategic planning']
    
    if not strategic_planning.empty:
        return strategic_planning.iloc[0]['Level 4 description']
    return "Not found"

def main():
    print("🔍 COMPARISON: Strategic Planning Level 4 Description")
    print("=" * 60)
    
    # App's answer
    app_answer = "Enables others to adapt and change in response to challenges and changes in the work environment."
    
    # Actual document content
    actual_content = get_actual_strategic_planning_level4()
    
    print("\n📱 APP'S ANSWER:")
    print("-" * 30)
    print(app_answer)
    
    print("\n📄 ACTUAL DOCUMENT CONTENT:")
    print("-" * 30)
    print(actual_content)
    
    print("\n" + "=" * 60)
    print("📊 ANALYSIS:")
    print("-" * 30)
    
    if app_answer in actual_content:
        print("✅ App's answer is PARTIALLY correct - it's a subset of the actual content")
    elif actual_content in app_answer:
        print("✅ App's answer is MORE DETAILED than the actual content")
    else:
        print("❌ App's answer is INCORRECT - it doesn't match the actual content")
    
    print(f"\n📏 Length comparison:")
    print(f"   App answer: {len(app_answer)} characters")
    print(f"   Actual content: {len(actual_content)} characters")
    
    print(f"\n🎯 Accuracy: The app provided a generic description that doesn't match")
    print("   the specific Level 4 description for Strategic planning in the document.")

if __name__ == "__main__":
    main() 