# Generated by AI on 2024-12-19
# Reviewed by: AI Assistant
# Ticket: SFIA-001

"""
SFIA - Semantic File Information Assistant
Main entry point for the restructured application.
"""

from src.interface.cli import main

if __name__ == "__main__":
    main() 