# Generated by AI on 2024-12-19
# Reviewed by: AI Assistant
# Ticket: SFIA-001

"""
Unit tests for domain models.
"""

import pytest

from src.domain.models.document import Document
from src.domain.models.query import Query
from src.domain.models.response import Response


class TestDocument:
    """Test cases for Document domain model."""
    
    def test_document_creation(self):
        """Test creating a valid document."""
        doc = Document(content="Test content")
        assert doc.content == "Test content"
        assert doc.metadata == {}
    
    def test_document_with_metadata(self):
        """Test creating a document with metadata."""
        metadata = {"source": "test.txt", "type": "text"}
        doc = Document(content="Test content", metadata=metadata)
        assert doc.metadata == metadata
    
    def test_document_validation_empty_content(self):
        """Test that empty content raises ValueError."""
        with pytest.raises(ValueError, match="Document content cannot be empty"):
            Document(content="")
    
    def test_document_validation_whitespace_content(self):
        """Test that whitespace-only content raises ValueError."""
        with pytest.raises(ValueError, match="Document content cannot be empty"):
            Document(content="   \n\t  ")
    
    def test_document_is_valid(self):
        """Test document validation method."""
        doc = Document(content="Valid content")
        assert doc.is_valid() is True
    
    def test_document_content_length(self):
        """Test getting document content length."""
        doc = Document(content="Test content")
        assert doc.get_content_length() == 12


class TestQuery:
    """Test cases for Query domain model."""
    
    def test_query_creation(self):
        """Test creating a valid query."""
        query = Query(text="Test question?")
        assert query.text == "Test question?"
        assert query.metadata == {}
    
    def test_query_validation_empty_text(self):
        """Test that empty text raises ValueError."""
        with pytest.raises(ValueError, match="Query text cannot be empty"):
            Query(text="")
    
    def test_query_is_valid(self):
        """Test query validation method."""
        query = Query(text="Valid question?")
        assert query.is_valid() is True
    
    def test_query_text_length(self):
        """Test getting query text length."""
        query = Query(text="Test question?")
        assert query.get_text_length() == 14


class TestResponse:
    """Test cases for Response domain model."""
    
    def test_response_creation(self):
        """Test creating a valid response."""
        response = Response(content="Test answer")
        assert response.content == "Test answer"
        assert response.metadata == {}
    
    def test_response_validation_empty_content(self):
        """Test that empty content raises ValueError."""
        with pytest.raises(ValueError, match="Response content cannot be empty"):
            Response(content="")
    
    def test_response_is_valid(self):
        """Test response validation method."""
        response = Response(content="Valid answer")
        assert response.is_valid() is True
    
    def test_response_content_length(self):
        """Test getting response content length."""
        response = Response(content="Test answer")
        assert response.get_content_length() == 11 