# Generated by AI on 2024-12-19
# Reviewed by: AI Assistant
# Ticket: SFIA-001

"""
Persistence layer exports.
"""

from .haystack_document_store import HaystackDocumentStore

__all__ = ["HaystackDocumentStore"] 