# Generated by AI on 2024-12-19
# Reviewed by: AI Assistant
# Ticket: SFIA-001

# Layer: domain
# Responsibility: Define document entity and its business rules
# Public API: Document(content, metadata)

from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class Document:
    """Domain entity representing a document with content and metadata."""
    
    content: str
    metadata: Optional[Dict[str, Any]] = None
    
    def __post_init__(self) -> None:
        """Validate document after initialization."""
        if not self.content or not self.content.strip():
            raise ValueError("Document content cannot be empty")
        
        if self.metadata is None:
            self.metadata = {}
    
    def is_valid(self) -> bool:
        """Check if document is valid for processing."""
        return bool(self.content and self.content.strip())
    
    def get_content_length(self) -> int:
        """Get the length of document content."""
        return len(self.content) 