# Generated by AI on 2024-12-19
# Reviewed by: AI Assistant
# Ticket: SFIA-001

# Layer: domain
# Responsibility: Define query entity and its business rules
# Public API: Query(text, metadata)

from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class Query:
    """Domain entity representing a user query."""
    
    text: str
    metadata: Optional[Dict[str, Any]] = None
    
    def __post_init__(self) -> None:
        """Validate query after initialization."""
        if not self.text or not self.text.strip():
            raise ValueError("Query text cannot be empty")
        
        if self.metadata is None:
            self.metadata = {}
    
    def is_valid(self) -> bool:
        """Check if query is valid for processing."""
        return bool(self.text and self.text.strip())
    
    def get_text_length(self) -> int:
        """Get the length of query text."""
        return len(self.text) 