# Generated by AI on 2024-12-19
# Reviewed by: AI Assistant
# Ticket: SFIA-001

# Layer: domain
# Responsibility: Define response entity and its business rules
# Public API: Response(content, metadata)

from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class Response:
    """Domain entity representing a response to a query."""
    
    content: str
    metadata: Optional[Dict[str, Any]] = None
    
    def __post_init__(self) -> None:
        """Validate response after initialization."""
        if not self.content or not self.content.strip():
            raise ValueError("Response content cannot be empty")
        
        if self.metadata is None:
            self.metadata = {}
    
    def is_valid(self) -> bool:
        """Check if response is valid."""
        return bool(self.content and self.content.strip())
    
    def get_content_length(self) -> int:
        """Get the length of response content."""
        return len(self.content) 